// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"universal-robots.com/urservice/client/urcap"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationUrcapAddUrcapCmd returns a cmd to handle operation addUrcap
func makeOperationUrcapAddUrcapCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "addUrcap",
		Short: `This operation install urcaps from a zipped urcap file. This operation 
expects zipped .urcapx file to be uploaded as form data.
`,
		RunE: runOperationUrcapAddUrcap,
	}

	if err := registerOperationUrcapAddUrcapParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationUrcapAddUrcap uses cmd flags to call endpoint api
func runOperationUrcapAddUrcap(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := urcap.NewAddUrcapParams()
	if err, _ := retrieveOperationUrcapAddUrcapUrcapxFileFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationUrcapAddUrcapResult(appCli.Urcap.AddUrcap(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationUrcapAddUrcapParamFlags registers all flags needed to fill params
func registerOperationUrcapAddUrcapParamFlags(cmd *cobra.Command) error {
	if err := registerOperationUrcapAddUrcapUrcapxFileParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationUrcapAddUrcapUrcapxFileParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	// warning: primitive urcapxFile io.ReadCloser is not supported by go-swagger cli yet

	return nil
}

func retrieveOperationUrcapAddUrcapUrcapxFileFlag(m *urcap.AddUrcapParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("urcapxFile") {

		// warning: primitive urcapxFile io.ReadCloser is not supported by go-swagger cli yet

	}
	return nil, retAdded
}

// parseOperationUrcapAddUrcapResult parses request result and return the string content
func parseOperationUrcapAddUrcapResult(resp0 *urcap.AddUrcapCreated, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*urcap.AddUrcapDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*urcap.AddUrcapCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
