// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetArtifactMetadataByPathURL generates an URL for the get artifact metadata by path operation
type GetArtifactMetadataByPathURL struct {
	ArtifactType string

	ArtifactPath string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetArtifactMetadataByPathURL) WithBasePath(bp string) *GetArtifactMetadataByPathURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetArtifactMetadataByPathURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetArtifactMetadataByPathURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/artifacts/{artifactType}/info"

	artifactType := o.ArtifactType
	if artifactType != "" {
		_path = strings.Replace(_path, "{artifactType}", artifactType, -1)
	} else {
		return nil, errors.New("artifactType is required on GetArtifactMetadataByPathURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	artifactPathQ := o.ArtifactPath
	if artifactPathQ != "" {
		qs.Set("artifactPath", artifactPathQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetArtifactMetadataByPathURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetArtifactMetadataByPathURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetArtifactMetadataByPathURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetArtifactMetadataByPathURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetArtifactMetadataByPathURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetArtifactMetadataByPathURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
