// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIError api error
//
// swagger:model apiError
type APIError struct {

	// The UUID to uniquely identifying the request
	// Example: 9daee671-916a-4678-850b-10b911f0236d
	Trace string `json:"trace,omitempty"`

	// HTTP status code used for the response
	// Example: 500
	StatusCode uint16 `json:"statusCode,omitempty"`

	// This field contains a snake case string succiently identifying the problem from api context.
	// Example: installation_failed
	// Required: true
	ErrorContext string `json:"errorContext"`

	// This field contains description of the problem
	Description string `json:"description,omitempty"`

	// This field explains a possible solution to the problem
	// Example: Please download urcapx file again and try installing again or contact urcap developer
	Resolve string `json:"resolve,omitempty"`

	// This filed contains a publicly-accessible URL where information about the error can be read in a web browser
	// Example: https://docs.api.example.com/v2/urcaps/installation#corrupted_file
	MoreInfo string `json:"moreInfo,omitempty"`

	// error code
	ErrorCode *ErrorCode `json:"errorCode,omitempty"`

	// List of errors
	// Required: true
	Errors []*Error `json:"errors"`
}

// Validate validates this api error
func (m *APIError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrorContext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrorCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIError) validateErrorContext(formats strfmt.Registry) error {

	if err := validate.RequiredString("errorContext", "body", m.ErrorContext); err != nil {
		return err
	}

	return nil
}

func (m *APIError) validateErrorCode(formats strfmt.Registry) error {
	if swag.IsZero(m.ErrorCode) { // not required
		return nil
	}

	if m.ErrorCode != nil {
		if err := m.ErrorCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errorCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errorCode")
			}
			return err
		}
	}

	return nil
}

func (m *APIError) validateErrors(formats strfmt.Registry) error {

	if err := validate.Required("errors", "body", m.Errors); err != nil {
		return err
	}

	for i := 0; i < len(m.Errors); i++ {
		if swag.IsZero(m.Errors[i]) { // not required
			continue
		}

		if m.Errors[i] != nil {
			if err := m.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this api error based on the context it is used
func (m *APIError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErrorCode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIError) contextValidateErrorCode(ctx context.Context, formats strfmt.Registry) error {

	if m.ErrorCode != nil {
		if err := m.ErrorCode.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errorCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errorCode")
			}
			return err
		}
	}

	return nil
}

func (m *APIError) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Errors); i++ {

		if m.Errors[i] != nil {
			if err := m.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIError) UnmarshalBinary(b []byte) error {
	var res APIError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
