// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContextError error and context
//
// swagger:model ContextError
type ContextError struct {

	// context of the error
	Context string `json:"context,omitempty" yaml:"context,omitempty"`

	// actual error
	Err error `json:"err,omitempty" yaml:"err,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ContextError) UnmarshalJSON(data []byte) error {
	var props struct {

		// context of the error
		Context string `json:"context,omitempty" yaml:"context,omitempty"`

		// actual error
		Err error `json:"err,omitempty" yaml:"err,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Context = props.Context
	m.Err = props.Err
	return nil
}

// Validate validates this context error
func (m *ContextError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this context error based on context it is used
func (m *ContextError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContextError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContextError) UnmarshalBinary(b []byte) error {
	var res ContextError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
