// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorCode error code
//
// swagger:model ErrorCode
type ErrorCode struct {

	// code
	Code int64 `json:"code,omitempty" yaml:"code,omitempty"`

	// field
	Field string `json:"field,omitempty" yaml:"field,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ErrorCode) UnmarshalJSON(data []byte) error {
	var props struct {

		// code
		Code int64 `json:"code,omitempty" yaml:"code,omitempty"`

		// field
		Field string `json:"field,omitempty" yaml:"field,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Code = props.Code
	m.Field = props.Field
	return nil
}

// Validate validates this error code
func (m *ErrorCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error code based on context it is used
func (m *ErrorCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorCode) UnmarshalBinary(b []byte) error {
	var res ErrorCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
