schemes:
    - https
swagger: "2.0"
info:
    description: API description in Markdown.
    title: Sample API
    version: 1.0.0
host: api.example.com
basePath: /v1
paths:
    /users:
        get:
            produces:
                - application/json
            summary: Returns a list of users.
            responses:
                "200":
                    description: manifest
                    schema:
                        $ref: '#/definitions/manifest'
                default:
                    description: error response
                    schema:
                        $ref: '#/definitions/apiError'
            description: Optional extended description in Markdown.
definitions:
    errorCode:
        type: object
        properties:
            major:
                description: API context
                type: integer
            minor:
                description: error context
                type: integer
    errorTarget:
        description: Error Target Model. This field MAY contain an error target model. Otherwise, it MUST be omitted.
        type: object
        required:
            - name
            - value
        properties:
            name:
                description: This field MUST contain field, parameter, or header
                type: string
                enum:
                    - field
                    - parameter
                    - header
                x-nullable: false
                x-order: !!float 0
                example: field
            value:
                type: string
                x-nullable: false
                x-order: !!float 1
                example: username
                description: This field MUST contain the name of the problematic field (with dot-syntax if necessary), query parameter, or header.
    manifest:
        description: |
            URCap Manifest Specification. The Manifest file is a YAML file defining a multi-artifacts based urcap application. The Manifest.yaml file is located on the top level directory/folder.
        type: object
        required:
            - apiVersion
            - metadata
        properties:
            apiVersion:
                description: "Version (major.minor.patch) of the Manifest specification used. Tools not implementing required version MUST reject the configuration file. \n"
                type: string
                pattern: ^[a-zA-Z0-9._-]+$
                x-nullable: false
                x-order: !!float 0
                example: 1.0.0
            metadata:
                $ref: '#/definitions/metadata'
    metadata:
        description: Metadata of the urcap
        type: object
        required:
            - vendorID
            - urcapID
            - urcapName
            - vendorName
            - version
        properties:
            urcapName:
                description: |
                    Urcap name of this application. This Will be displayed on user interface.
                type: string
                maxLength: !!float 20
                minLength: !!float 3
                pattern: ^[a-zA-Z0-9_\-\s]+$
                x-nullable: false
                x-order: !!float 5
                example: Docker Daemon
            vendorID:
                x-nullable: false
                x-order: !!float 0
                example: universal-robots
                description: |
                    Company urcap developer ID. The ID is shared among all urcap applications developed by company.
                type: string
                maxLength: !!float 27
                minLength: !!float 2
                pattern: ^[a-zA-Z0-9._-]+$
            vendorName:
                example: Universal Robots
                description: |
                    Urcap name of this application. This Will be displayed on user interface.
                type: string
                maxLength: !!float 27
                minLength: !!float 4
                pattern: ^[a-zA-Z0-9_\-\s]+$
                x-nullable: false
                x-order: !!float 3
            version:
                x-nullable: false
                x-order: !!float 2
                example: 1.0.0
                description: |
                    Urcap version (major.minor.patch)
                type: string
                pattern: ^\d{1}.\d{1}.\d{1}$
            copyright:
                x-nullable: false
                x-order: !!float 7
                example: Copyright (c) 2009-2021 Universal Robots. All rights reserved.
                description: Specifies copy rights for the urcap
                type: string
            description:
                type: string
                x-nullable: false
                x-order: !!float 6
                example: Sample gripper URCap
                description: Short description of urcap
            license:
                x-order: !!float 8
                example: TODO
                description: License of various software/hardware used while developing the urcap
                type: string
                x-nullable: false
            urcapID:
                x-order: !!float 1
                example: dockerdaemon
                description: |
                    Urcap id for this application. The ID must be unique for each urcap application developed by a company (vendorID).
                type: string
                maxLength: !!float 27
                minLength: !!float 2
                pattern: ^[a-zA-Z0-9._-]+$
                x-nullable: false
    apiError:
        type: object
        required:
            - apiContext
            - errors
        properties:
            resolve:
                description: This field explains a possible solution to the problem
                type: string
                x-order: !!float 5
                example: Please download urcapx file again and try installing again or contact urcap developer
            statusCode:
                x-order: !!float 1
                example: !!float 500
                description: HTTP status code used for the response
                type: integer
                format: uint16
            trace:
                type: string
                x-order: !!float 0
                example: 9daee671-916a-4678-850b-10b911f0236d
                description: The UUID to uniquely identifying the request
            description:
                type: string
                x-order: !!float 4
                description: This field contains description of the problem
            errorCode:
                $ref: '#/definitions/errorCode'
            errorContext:
                description: This field contains a snake case string succiently identifying the problem from api context.
                type: string
                x-nullable: false
                x-order: !!float 3
                example: installation_failed
            errors:
                description: List of errors
                type: array
                items:
                    $ref: '#/definitions/error'
            moreInfo:
                description: This filed contains a publicly-accessible URL where information about the error can be read in a web browser
                type: string
                format: url
                x-order: !!float 6
                example: https://docs.api.example.com/v2/urcaps/installation#corrupted_file
    error:
        type: object
        properties:
            message:
                description: This field contain a plainly-written, developer-oriented explanation of the solution to the problem in complete, well-formed sentences.
                type: string
                x-go-type:
                    hints:
                        kind: interface
                    type: error
                x-nullable: false
                x-order: !!float 1
                example: The `first_name` field is required.
            more_info:
                x-order: !!float 2
                example: https://docs.api.example.com/v2/users/create_user#first_name
                description: This field SHOULD contain a publicly-accessible URL where information about the error can be read in a web browser.
                type: string
                format: url
                x-nullable: false
            target:
                $ref: '#/definitions/errorTarget'
            code:
                x-nullable: false
                x-order: !!float 0
                example: missing_field
                description: |
                    Error codes.This field contains a string succinctly identifying     the problem.
                type: string
        description: api error
