// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// GetContainerPortMappingByIDOKCode is the HTTP code returned for type GetContainerPortMappingByIDOK
const GetContainerPortMappingByIDOKCode int = 200

/*
GetContainerPortMappingByIDOK Container Port Mapping.

swagger:response getContainerPortMappingByIdOK
*/
type GetContainerPortMappingByIDOK struct {
}

// NewGetContainerPortMappingByIDOK creates GetContainerPortMappingByIDOK with default headers values
func NewGetContainerPortMappingByIDOK() *GetContainerPortMappingByIDOK {

	return &GetContainerPortMappingByIDOK{}
}

// WriteResponse to the client
func (o *GetContainerPortMappingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *GetContainerPortMappingByIDOK) GetContainerPortMappingByIDResponder() {}

/*
GetContainerPortMappingByIDDefault error

swagger:response getContainerPortMappingByIdDefault
*/
type GetContainerPortMappingByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetContainerPortMappingByIDDefault creates GetContainerPortMappingByIDDefault with default headers values
func NewGetContainerPortMappingByIDDefault(code int) *GetContainerPortMappingByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetContainerPortMappingByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get container port mapping by Id default response
func (o *GetContainerPortMappingByIDDefault) WithStatusCode(code int) *GetContainerPortMappingByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get container port mapping by Id default response
func (o *GetContainerPortMappingByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get container port mapping by Id default response
func (o *GetContainerPortMappingByIDDefault) WithPayload(payload *models.ErrorResponse) *GetContainerPortMappingByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container port mapping by Id default response
func (o *GetContainerPortMappingByIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerPortMappingByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetContainerPortMappingByIDDefault) GetContainerPortMappingByIDResponder() {}

type GetContainerPortMappingByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*GetContainerPortMappingByIDNotImplementedResponder) GetContainerPortMappingByIDResponder() {}

func GetContainerPortMappingByIDNotImplemented() GetContainerPortMappingByIDResponder {
	return &GetContainerPortMappingByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetContainerPortMappingByID has not yet been implemented",
		),
	}
}

type GetContainerPortMappingByIDResponder interface {
	middleware.Responder
	GetContainerPortMappingByIDResponder()
}
