// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// StartContainerByIDOKCode is the HTTP code returned for type StartContainerByIDOK
const StartContainerByIDOKCode int = 200

/*
StartContainerByIDOK OK

swagger:response startContainerByIdOK
*/
type StartContainerByIDOK struct {
}

// NewStartContainerByIDOK creates StartContainerByIDOK with default headers values
func NewStartContainerByIDOK() *StartContainerByIDOK {

	return &StartContainerByIDOK{}
}

// WriteResponse to the client
func (o *StartContainerByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *StartContainerByIDOK) StartContainerByIDResponder() {}

/*
StartContainerByIDDefault error

swagger:response startContainerByIdDefault
*/
type StartContainerByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewStartContainerByIDDefault creates StartContainerByIDDefault with default headers values
func NewStartContainerByIDDefault(code int) *StartContainerByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &StartContainerByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the start container by Id default response
func (o *StartContainerByIDDefault) WithStatusCode(code int) *StartContainerByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the start container by Id default response
func (o *StartContainerByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the start container by Id default response
func (o *StartContainerByIDDefault) WithPayload(payload *models.ErrorResponse) *StartContainerByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start container by Id default response
func (o *StartContainerByIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartContainerByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *StartContainerByIDDefault) StartContainerByIDResponder() {}

type StartContainerByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*StartContainerByIDNotImplementedResponder) StartContainerByIDResponder() {}

func StartContainerByIDNotImplemented() StartContainerByIDResponder {
	return &StartContainerByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.StartContainerByID has not yet been implemented",
		),
	}
}

type StartContainerByIDResponder interface {
	middleware.Responder
	StartContainerByIDResponder()
}
