// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// StartContainerByIDURL generates an URL for the start container by Id operation
type StartContainerByIDURL struct {
	ArtifactName string
	UrcapID      string
	VendorID     string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *StartContainerByIDURL) WithBasePath(bp string) *StartContainerByIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *StartContainerByIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *StartContainerByIDURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/containers/{vendorID}/{urcapID}/{artifactName}/start"

	artifactName := o.ArtifactName
	if artifactName != "" {
		_path = strings.Replace(_path, "{artifactName}", artifactName, -1)
	} else {
		return nil, errors.New("artifactName is required on StartContainerByIDURL")
	}

	urcapID := o.UrcapID
	if urcapID != "" {
		_path = strings.Replace(_path, "{urcapID}", urcapID, -1)
	} else {
		return nil, errors.New("urcapId is required on StartContainerByIDURL")
	}

	vendorID := o.VendorID
	if vendorID != "" {
		_path = strings.Replace(_path, "{vendorID}", vendorID, -1)
	} else {
		return nil, errors.New("vendorId is required on StartContainerByIDURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *StartContainerByIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *StartContainerByIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *StartContainerByIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on StartContainerByIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on StartContainerByIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *StartContainerByIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
