// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"universal-robots.com/urservice/models"
)

// GetContainerByIDReader is a Reader for the GetContainerByID structure.
type GetContainerByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContainerByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContainerByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetContainerByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetContainerByIDOK creates a GetContainerByIDOK with default headers values
func NewGetContainerByIDOK() *GetContainerByIDOK {
	return &GetContainerByIDOK{}
}

/*
GetContainerByIDOK describes a response with status code 200, with default header values.

A single container.
*/
type GetContainerByIDOK struct {
	Payload *models.Container
}

// IsSuccess returns true when this get container by Id o k response has a 2xx status code
func (o *GetContainerByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get container by Id o k response has a 3xx status code
func (o *GetContainerByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get container by Id o k response has a 4xx status code
func (o *GetContainerByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get container by Id o k response has a 5xx status code
func (o *GetContainerByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get container by Id o k response a status code equal to that given
func (o *GetContainerByIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetContainerByIDOK) Error() string {
	return fmt.Sprintf("[GET /containers/{vendorID}/{urcapID}/{artifactName}][%d] getContainerByIdOK  %+v", 200, o.Payload)
}

func (o *GetContainerByIDOK) String() string {
	return fmt.Sprintf("[GET /containers/{vendorID}/{urcapID}/{artifactName}][%d] getContainerByIdOK  %+v", 200, o.Payload)
}

func (o *GetContainerByIDOK) GetPayload() *models.Container {
	return o.Payload
}

func (o *GetContainerByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Container)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContainerByIDDefault creates a GetContainerByIDDefault with default headers values
func NewGetContainerByIDDefault(code int) *GetContainerByIDDefault {
	return &GetContainerByIDDefault{
		_statusCode: code,
	}
}

/*
GetContainerByIDDefault describes a response with status code -1, with default header values.

error
*/
type GetContainerByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get container by Id default response
func (o *GetContainerByIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get container by Id default response has a 2xx status code
func (o *GetContainerByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get container by Id default response has a 3xx status code
func (o *GetContainerByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get container by Id default response has a 4xx status code
func (o *GetContainerByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get container by Id default response has a 5xx status code
func (o *GetContainerByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get container by Id default response a status code equal to that given
func (o *GetContainerByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetContainerByIDDefault) Error() string {
	return fmt.Sprintf("[GET /containers/{vendorID}/{urcapID}/{artifactName}][%d] getContainerById default  %+v", o._statusCode, o.Payload)
}

func (o *GetContainerByIDDefault) String() string {
	return fmt.Sprintf("[GET /containers/{vendorID}/{urcapID}/{artifactName}][%d] getContainerById default  %+v", o._statusCode, o.Payload)
}

func (o *GetContainerByIDDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetContainerByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
