// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopAllContainersParams creates a new StopAllContainersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopAllContainersParams() *StopAllContainersParams {
	return &StopAllContainersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopAllContainersParamsWithTimeout creates a new StopAllContainersParams object
// with the ability to set a timeout on a request.
func NewStopAllContainersParamsWithTimeout(timeout time.Duration) *StopAllContainersParams {
	return &StopAllContainersParams{
		timeout: timeout,
	}
}

// NewStopAllContainersParamsWithContext creates a new StopAllContainersParams object
// with the ability to set a context for a request.
func NewStopAllContainersParamsWithContext(ctx context.Context) *StopAllContainersParams {
	return &StopAllContainersParams{
		Context: ctx,
	}
}

// NewStopAllContainersParamsWithHTTPClient creates a new StopAllContainersParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopAllContainersParamsWithHTTPClient(client *http.Client) *StopAllContainersParams {
	return &StopAllContainersParams{
		HTTPClient: client,
	}
}

/*
StopAllContainersParams contains all the parameters to send to the API endpoint

	for the stop all containers operation.

	Typically these are written to a http.Request.
*/
type StopAllContainersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop all containers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopAllContainersParams) WithDefaults() *StopAllContainersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop all containers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopAllContainersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop all containers params
func (o *StopAllContainersParams) WithTimeout(timeout time.Duration) *StopAllContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop all containers params
func (o *StopAllContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop all containers params
func (o *StopAllContainersParams) WithContext(ctx context.Context) *StopAllContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop all containers params
func (o *StopAllContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop all containers params
func (o *StopAllContainersParams) WithHTTPClient(client *http.Client) *StopAllContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop all containers params
func (o *StopAllContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StopAllContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
