// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopContainerByIDParams creates a new StopContainerByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopContainerByIDParams() *StopContainerByIDParams {
	return &StopContainerByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopContainerByIDParamsWithTimeout creates a new StopContainerByIDParams object
// with the ability to set a timeout on a request.
func NewStopContainerByIDParamsWithTimeout(timeout time.Duration) *StopContainerByIDParams {
	return &StopContainerByIDParams{
		timeout: timeout,
	}
}

// NewStopContainerByIDParamsWithContext creates a new StopContainerByIDParams object
// with the ability to set a context for a request.
func NewStopContainerByIDParamsWithContext(ctx context.Context) *StopContainerByIDParams {
	return &StopContainerByIDParams{
		Context: ctx,
	}
}

// NewStopContainerByIDParamsWithHTTPClient creates a new StopContainerByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopContainerByIDParamsWithHTTPClient(client *http.Client) *StopContainerByIDParams {
	return &StopContainerByIDParams{
		HTTPClient: client,
	}
}

/*
StopContainerByIDParams contains all the parameters to send to the API endpoint

	for the stop container by Id operation.

	Typically these are written to a http.Request.
*/
type StopContainerByIDParams struct {

	/* ArtifactName.

	   artifact name of container defined in manifest
	*/
	ArtifactName string

	/* UrcapID.

	   urcapID of urcap defined in manifest
	*/
	UrcapID string

	/* VendorID.

	   vendorID of urcap defined in manifest
	*/
	VendorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopContainerByIDParams) WithDefaults() *StopContainerByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopContainerByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop container by Id params
func (o *StopContainerByIDParams) WithTimeout(timeout time.Duration) *StopContainerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop container by Id params
func (o *StopContainerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop container by Id params
func (o *StopContainerByIDParams) WithContext(ctx context.Context) *StopContainerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop container by Id params
func (o *StopContainerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop container by Id params
func (o *StopContainerByIDParams) WithHTTPClient(client *http.Client) *StopContainerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop container by Id params
func (o *StopContainerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifactName adds the artifactName to the stop container by Id params
func (o *StopContainerByIDParams) WithArtifactName(artifactName string) *StopContainerByIDParams {
	o.SetArtifactName(artifactName)
	return o
}

// SetArtifactName adds the artifactName to the stop container by Id params
func (o *StopContainerByIDParams) SetArtifactName(artifactName string) {
	o.ArtifactName = artifactName
}

// WithUrcapID adds the urcapID to the stop container by Id params
func (o *StopContainerByIDParams) WithUrcapID(urcapID string) *StopContainerByIDParams {
	o.SetUrcapID(urcapID)
	return o
}

// SetUrcapID adds the urcapId to the stop container by Id params
func (o *StopContainerByIDParams) SetUrcapID(urcapID string) {
	o.UrcapID = urcapID
}

// WithVendorID adds the vendorID to the stop container by Id params
func (o *StopContainerByIDParams) WithVendorID(vendorID string) *StopContainerByIDParams {
	o.SetVendorID(vendorID)
	return o
}

// SetVendorID adds the vendorId to the stop container by Id params
func (o *StopContainerByIDParams) SetVendorID(vendorID string) {
	o.VendorID = vendorID
}

// WriteToRequest writes these params to a swagger request
func (o *StopContainerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param artifactName
	if err := r.SetPathParam("artifactName", o.ArtifactName); err != nil {
		return err
	}

	// path param urcapID
	if err := r.SetPathParam("urcapID", o.UrcapID); err != nil {
		return err
	}

	// path param vendorID
	if err := r.SetPathParam("vendorID", o.VendorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
