// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"universal-robots/urcapctl/client/urcap"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationUrcapBuildCmd returns a cmd to handle operation build
func makeOperationUrcapBuildCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "build",
		Short: `Build's urcap given path to the urcap source folder containing manifest.yaml`,
		RunE:  runOperationUrcapBuild,
	}

	if err := registerOperationUrcapBuildParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationUrcapBuild uses cmd flags to call endpoint api
func runOperationUrcapBuild(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := urcap.NewBuildParams()
	if err, _ := retrieveOperationUrcapBuildPathFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationUrcapBuildResult(appCli.Urcap.Build(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationUrcapBuildParamFlags registers all flags needed to fill params
func registerOperationUrcapBuildParamFlags(cmd *cobra.Command) error {
	if err := registerOperationUrcapBuildPathParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationUrcapBuildPathParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pathDescription := `Required. path to urcap source folder containing manifest.yaml`

	var pathFlagName string
	if cmdPrefix == "" {
		pathFlagName = "path"
	} else {
		pathFlagName = fmt.Sprintf("%v.path", cmdPrefix)
	}

	var pathFlagDefault string

	_ = cmd.PersistentFlags().String(pathFlagName, pathFlagDefault, pathDescription)

	return nil
}

func retrieveOperationUrcapBuildPathFlag(m *urcap.BuildParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("path") {

		var pathFlagName string
		if cmdPrefix == "" {
			pathFlagName = "path"
		} else {
			pathFlagName = fmt.Sprintf("%v.path", cmdPrefix)
		}

		pathFlagValue, err := cmd.Flags().GetString(pathFlagName)
		if err != nil {
			return err, false
		}
		m.Path = pathFlagValue

	}
	return nil, retAdded
}

// parseOperationUrcapBuildResult parses request result and return the string content
func parseOperationUrcapBuildResult(resp0 *urcap.BuildOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*urcap.BuildDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning buildOK is not supported

		return "", respErr
	}

	// warning: non schema response buildOK is not supported by go-swagger cli yet.

	return "", nil
}
