// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"universal-robots.com/urservice/models"
)

// DeleteUrcapByIDReader is a Reader for the DeleteUrcapByID structure.
type DeleteUrcapByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUrcapByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUrcapByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteUrcapByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteUrcapByIDOK creates a DeleteUrcapByIDOK with default headers values
func NewDeleteUrcapByIDOK() *DeleteUrcapByIDOK {
	return &DeleteUrcapByIDOK{}
}

/*
DeleteUrcapByIDOK describes a response with status code 200, with default header values.

Updated urcap.
*/
type DeleteUrcapByIDOK struct {
	Payload *models.Manifest
}

// IsSuccess returns true when this delete urcap by Id o k response has a 2xx status code
func (o *DeleteUrcapByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete urcap by Id o k response has a 3xx status code
func (o *DeleteUrcapByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete urcap by Id o k response has a 4xx status code
func (o *DeleteUrcapByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete urcap by Id o k response has a 5xx status code
func (o *DeleteUrcapByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete urcap by Id o k response a status code equal to that given
func (o *DeleteUrcapByIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteUrcapByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /urcaps/{vendorID}/{urcapID}][%d] deleteUrcapByIdOK  %+v", 200, o.Payload)
}

func (o *DeleteUrcapByIDOK) String() string {
	return fmt.Sprintf("[DELETE /urcaps/{vendorID}/{urcapID}][%d] deleteUrcapByIdOK  %+v", 200, o.Payload)
}

func (o *DeleteUrcapByIDOK) GetPayload() *models.Manifest {
	return o.Payload
}

func (o *DeleteUrcapByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Manifest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUrcapByIDDefault creates a DeleteUrcapByIDDefault with default headers values
func NewDeleteUrcapByIDDefault(code int) *DeleteUrcapByIDDefault {
	return &DeleteUrcapByIDDefault{
		_statusCode: code,
	}
}

/*
DeleteUrcapByIDDefault describes a response with status code -1, with default header values.

error
*/
type DeleteUrcapByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete urcap by Id default response
func (o *DeleteUrcapByIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete urcap by Id default response has a 2xx status code
func (o *DeleteUrcapByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete urcap by Id default response has a 3xx status code
func (o *DeleteUrcapByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete urcap by Id default response has a 4xx status code
func (o *DeleteUrcapByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete urcap by Id default response has a 5xx status code
func (o *DeleteUrcapByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete urcap by Id default response a status code equal to that given
func (o *DeleteUrcapByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteUrcapByIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /urcaps/{vendorID}/{urcapID}][%d] deleteUrcapById default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteUrcapByIDDefault) String() string {
	return fmt.Sprintf("[DELETE /urcaps/{vendorID}/{urcapID}][%d] deleteUrcapById default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteUrcapByIDDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteUrcapByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
