// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUrcapsParams creates a new GetUrcapsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUrcapsParams() *GetUrcapsParams {
	return &GetUrcapsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUrcapsParamsWithTimeout creates a new GetUrcapsParams object
// with the ability to set a timeout on a request.
func NewGetUrcapsParamsWithTimeout(timeout time.Duration) *GetUrcapsParams {
	return &GetUrcapsParams{
		timeout: timeout,
	}
}

// NewGetUrcapsParamsWithContext creates a new GetUrcapsParams object
// with the ability to set a context for a request.
func NewGetUrcapsParamsWithContext(ctx context.Context) *GetUrcapsParams {
	return &GetUrcapsParams{
		Context: ctx,
	}
}

// NewGetUrcapsParamsWithHTTPClient creates a new GetUrcapsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUrcapsParamsWithHTTPClient(client *http.Client) *GetUrcapsParams {
	return &GetUrcapsParams{
		HTTPClient: client,
	}
}

/*
GetUrcapsParams contains all the parameters to send to the API endpoint

	for the get urcaps operation.

	Typically these are written to a http.Request.
*/
type GetUrcapsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get urcaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUrcapsParams) WithDefaults() *GetUrcapsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get urcaps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUrcapsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get urcaps params
func (o *GetUrcapsParams) WithTimeout(timeout time.Duration) *GetUrcapsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get urcaps params
func (o *GetUrcapsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get urcaps params
func (o *GetUrcapsParams) WithContext(ctx context.Context) *GetUrcapsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get urcaps params
func (o *GetUrcapsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get urcaps params
func (o *GetUrcapsParams) WithHTTPClient(client *http.Client) *GetUrcapsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get urcaps params
func (o *GetUrcapsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUrcapsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
