// Code generated by go-swagger; DO NOT EDIT.

// Package restapi urcap API
//
//	API description for URCaps.
//	Schemes:
//	  http
//	Host: localhost:8181
//	BasePath: /api/v1
//	Version: 1.0.0
//	License: Apache '2.0' http://www.apache.org/licenses/LICENSE
//	Contact: Universal Robots<swpl@universal-robots.com> https://www.universal-robots.com/
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
