// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddUrcapParams creates a new AddUrcapParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddUrcapParams() *AddUrcapParams {
	return &AddUrcapParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddUrcapParamsWithTimeout creates a new AddUrcapParams object
// with the ability to set a timeout on a request.
func NewAddUrcapParamsWithTimeout(timeout time.Duration) *AddUrcapParams {
	return &AddUrcapParams{
		timeout: timeout,
	}
}

// NewAddUrcapParamsWithContext creates a new AddUrcapParams object
// with the ability to set a context for a request.
func NewAddUrcapParamsWithContext(ctx context.Context) *AddUrcapParams {
	return &AddUrcapParams{
		Context: ctx,
	}
}

// NewAddUrcapParamsWithHTTPClient creates a new AddUrcapParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddUrcapParamsWithHTTPClient(client *http.Client) *AddUrcapParams {
	return &AddUrcapParams{
		HTTPClient: client,
	}
}

/*
AddUrcapParams contains all the parameters to send to the API endpoint

	for the add urcap operation.

	Typically these are written to a http.Request.
*/
type AddUrcapParams struct {

	/* UrcapxFile.

	   The zipped urcapx file.

	*/
	UrcapxFile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add urcap params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUrcapParams) WithDefaults() *AddUrcapParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add urcap params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUrcapParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add urcap params
func (o *AddUrcapParams) WithTimeout(timeout time.Duration) *AddUrcapParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add urcap params
func (o *AddUrcapParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add urcap params
func (o *AddUrcapParams) WithContext(ctx context.Context) *AddUrcapParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add urcap params
func (o *AddUrcapParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add urcap params
func (o *AddUrcapParams) WithHTTPClient(client *http.Client) *AddUrcapParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add urcap params
func (o *AddUrcapParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrcapxFile adds the urcapxFile to the add urcap params
func (o *AddUrcapParams) WithUrcapxFile(urcapxFile runtime.NamedReadCloser) *AddUrcapParams {
	o.SetUrcapxFile(urcapxFile)
	return o
}

// SetUrcapxFile adds the urcapxFile to the add urcap params
func (o *AddUrcapParams) SetUrcapxFile(urcapxFile runtime.NamedReadCloser) {
	o.UrcapxFile = urcapxFile
}

// WriteToRequest writes these params to a swagger request
func (o *AddUrcapParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param urcapxFile
	if err := r.SetFileParam("urcapxFile", o.UrcapxFile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
