// Code generated by go-swagger; DO NOT EDIT.

package artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"urcapCli/models"
)

// GetArtifactActualNameByPathReader is a Reader for the GetArtifactActualNameByPath structure.
type GetArtifactActualNameByPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArtifactActualNameByPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetArtifactActualNameByPathOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetArtifactActualNameByPathDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetArtifactActualNameByPathOK creates a GetArtifactActualNameByPathOK with default headers values
func NewGetArtifactActualNameByPathOK() *GetArtifactActualNameByPathOK {
	return &GetArtifactActualNameByPathOK{}
}

/*
GetArtifactActualNameByPathOK describes a response with status code 200, with default header values.

artifact name
*/
type GetArtifactActualNameByPathOK struct {
	Payload string
}

// IsSuccess returns true when this get artifact actual name by path o k response has a 2xx status code
func (o *GetArtifactActualNameByPathOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get artifact actual name by path o k response has a 3xx status code
func (o *GetArtifactActualNameByPathOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get artifact actual name by path o k response has a 4xx status code
func (o *GetArtifactActualNameByPathOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get artifact actual name by path o k response has a 5xx status code
func (o *GetArtifactActualNameByPathOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get artifact actual name by path o k response a status code equal to that given
func (o *GetArtifactActualNameByPathOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetArtifactActualNameByPathOK) Error() string {
	return fmt.Sprintf("[GET /artifacts/{artifactType}/name][%d] getArtifactActualNameByPathOK  %+v", 200, o.Payload)
}

func (o *GetArtifactActualNameByPathOK) String() string {
	return fmt.Sprintf("[GET /artifacts/{artifactType}/name][%d] getArtifactActualNameByPathOK  %+v", 200, o.Payload)
}

func (o *GetArtifactActualNameByPathOK) GetPayload() string {
	return o.Payload
}

func (o *GetArtifactActualNameByPathOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactActualNameByPathDefault creates a GetArtifactActualNameByPathDefault with default headers values
func NewGetArtifactActualNameByPathDefault(code int) *GetArtifactActualNameByPathDefault {
	return &GetArtifactActualNameByPathDefault{
		_statusCode: code,
	}
}

/*
GetArtifactActualNameByPathDefault describes a response with status code -1, with default header values.

api error
*/
type GetArtifactActualNameByPathDefault struct {
	_statusCode int

	Payload *models.APIError
}

// Code gets the status code for the get artifact actual name by path default response
func (o *GetArtifactActualNameByPathDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get artifact actual name by path default response has a 2xx status code
func (o *GetArtifactActualNameByPathDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get artifact actual name by path default response has a 3xx status code
func (o *GetArtifactActualNameByPathDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get artifact actual name by path default response has a 4xx status code
func (o *GetArtifactActualNameByPathDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get artifact actual name by path default response has a 5xx status code
func (o *GetArtifactActualNameByPathDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get artifact actual name by path default response a status code equal to that given
func (o *GetArtifactActualNameByPathDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetArtifactActualNameByPathDefault) Error() string {
	return fmt.Sprintf("[GET /artifacts/{artifactType}/name][%d] getArtifactActualNameByPath default  %+v", o._statusCode, o.Payload)
}

func (o *GetArtifactActualNameByPathDefault) String() string {
	return fmt.Sprintf("[GET /artifacts/{artifactType}/name][%d] getArtifactActualNameByPath default  %+v", o._statusCode, o.Payload)
}

func (o *GetArtifactActualNameByPathDefault) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetArtifactActualNameByPathDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
