// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// DeleteUrcapByIDOKCode is the HTTP code returned for type DeleteUrcapByIDOK
const DeleteUrcapByIDOKCode int = 200

/*
DeleteUrcapByIDOK Updated urcap.

swagger:response deleteUrcapByIdOK
*/
type DeleteUrcapByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Manifest `json:"body,omitempty"`
}

// NewDeleteUrcapByIDOK creates DeleteUrcapByIDOK with default headers values
func NewDeleteUrcapByIDOK() *DeleteUrcapByIDOK {

	return &DeleteUrcapByIDOK{}
}

// WithPayload adds the payload to the delete urcap by Id o k response
func (o *DeleteUrcapByIDOK) WithPayload(payload *models.Manifest) *DeleteUrcapByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete urcap by Id o k response
func (o *DeleteUrcapByIDOK) SetPayload(payload *models.Manifest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUrcapByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteUrcapByIDOK) DeleteUrcapByIDResponder() {}

/*
DeleteUrcapByIDDefault error

swagger:response deleteUrcapByIdDefault
*/
type DeleteUrcapByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteUrcapByIDDefault creates DeleteUrcapByIDDefault with default headers values
func NewDeleteUrcapByIDDefault(code int) *DeleteUrcapByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUrcapByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete urcap by Id default response
func (o *DeleteUrcapByIDDefault) WithStatusCode(code int) *DeleteUrcapByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete urcap by Id default response
func (o *DeleteUrcapByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete urcap by Id default response
func (o *DeleteUrcapByIDDefault) WithPayload(payload *models.ErrorResponse) *DeleteUrcapByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete urcap by Id default response
func (o *DeleteUrcapByIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUrcapByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteUrcapByIDDefault) DeleteUrcapByIDResponder() {}

type DeleteUrcapByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteUrcapByIDNotImplementedResponder) DeleteUrcapByIDResponder() {}

func DeleteUrcapByIDNotImplemented() DeleteUrcapByIDResponder {
	return &DeleteUrcapByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteUrcapByID has not yet been implemented",
		),
	}
}

type DeleteUrcapByIDResponder interface {
	middleware.Responder
	DeleteUrcapByIDResponder()
}
