// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// GetUrcapByIDOKCode is the HTTP code returned for type GetUrcapByIDOK
const GetUrcapByIDOKCode int = 200

/*
GetUrcapByIDOK A single urcap.

swagger:response getUrcapByIdOK
*/
type GetUrcapByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Manifest `json:"body,omitempty"`
}

// NewGetUrcapByIDOK creates GetUrcapByIDOK with default headers values
func NewGetUrcapByIDOK() *GetUrcapByIDOK {

	return &GetUrcapByIDOK{}
}

// WithPayload adds the payload to the get urcap by Id o k response
func (o *GetUrcapByIDOK) WithPayload(payload *models.Manifest) *GetUrcapByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get urcap by Id o k response
func (o *GetUrcapByIDOK) SetPayload(payload *models.Manifest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUrcapByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetUrcapByIDOK) GetUrcapByIDResponder() {}

/*
GetUrcapByIDDefault error

swagger:response getUrcapByIdDefault
*/
type GetUrcapByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetUrcapByIDDefault creates GetUrcapByIDDefault with default headers values
func NewGetUrcapByIDDefault(code int) *GetUrcapByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUrcapByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get urcap by Id default response
func (o *GetUrcapByIDDefault) WithStatusCode(code int) *GetUrcapByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get urcap by Id default response
func (o *GetUrcapByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get urcap by Id default response
func (o *GetUrcapByIDDefault) WithPayload(payload *models.ErrorResponse) *GetUrcapByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get urcap by Id default response
func (o *GetUrcapByIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUrcapByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetUrcapByIDDefault) GetUrcapByIDResponder() {}

type GetUrcapByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*GetUrcapByIDNotImplementedResponder) GetUrcapByIDResponder() {}

func GetUrcapByIDNotImplemented() GetUrcapByIDResponder {
	return &GetUrcapByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetUrcapByID has not yet been implemented",
		),
	}
}

type GetUrcapByIDResponder interface {
	middleware.Responder
	GetUrcapByIDResponder()
}
