// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// GetUrcapsOKCode is the HTTP code returned for type GetUrcapsOK
const GetUrcapsOKCode int = 200

/*
GetUrcapsOK OK

swagger:response getUrcapsOK
*/
type GetUrcapsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Manifest `json:"body,omitempty"`
}

// NewGetUrcapsOK creates GetUrcapsOK with default headers values
func NewGetUrcapsOK() *GetUrcapsOK {

	return &GetUrcapsOK{}
}

// WithPayload adds the payload to the get urcaps o k response
func (o *GetUrcapsOK) WithPayload(payload []*models.Manifest) *GetUrcapsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get urcaps o k response
func (o *GetUrcapsOK) SetPayload(payload []*models.Manifest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUrcapsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Manifest, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *GetUrcapsOK) GetUrcapsResponder() {}

type GetUrcapsNotImplementedResponder struct {
	middleware.Responder
}

func (*GetUrcapsNotImplementedResponder) GetUrcapsResponder() {}

func GetUrcapsNotImplemented() GetUrcapsResponder {
	return &GetUrcapsNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetUrcaps has not yet been implemented",
		),
	}
}

type GetUrcapsResponder interface {
	middleware.Responder
	GetUrcapsResponder()
}
