// Code generated by go-swagger; DO NOT EDIT.

package urcap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"universal-robots.com/urservice/models"
)

// UpdateUrcapByIDOKCode is the HTTP code returned for type UpdateUrcapByIDOK
const UpdateUrcapByIDOKCode int = 200

/*
UpdateUrcapByIDOK Updated urcap.

swagger:response updateUrcapByIdOK
*/
type UpdateUrcapByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Manifest `json:"body,omitempty"`
}

// NewUpdateUrcapByIDOK creates UpdateUrcapByIDOK with default headers values
func NewUpdateUrcapByIDOK() *UpdateUrcapByIDOK {

	return &UpdateUrcapByIDOK{}
}

// WithPayload adds the payload to the update urcap by Id o k response
func (o *UpdateUrcapByIDOK) WithPayload(payload *models.Manifest) *UpdateUrcapByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update urcap by Id o k response
func (o *UpdateUrcapByIDOK) SetPayload(payload *models.Manifest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUrcapByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *UpdateUrcapByIDOK) UpdateUrcapByIDResponder() {}

/*
UpdateUrcapByIDDefault error

swagger:response updateUrcapByIdDefault
*/
type UpdateUrcapByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateUrcapByIDDefault creates UpdateUrcapByIDDefault with default headers values
func NewUpdateUrcapByIDDefault(code int) *UpdateUrcapByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUrcapByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update urcap by Id default response
func (o *UpdateUrcapByIDDefault) WithStatusCode(code int) *UpdateUrcapByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update urcap by Id default response
func (o *UpdateUrcapByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update urcap by Id default response
func (o *UpdateUrcapByIDDefault) WithPayload(payload *models.ErrorResponse) *UpdateUrcapByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update urcap by Id default response
func (o *UpdateUrcapByIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUrcapByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *UpdateUrcapByIDDefault) UpdateUrcapByIDResponder() {}

type UpdateUrcapByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*UpdateUrcapByIDNotImplementedResponder) UpdateUrcapByIDResponder() {}

func UpdateUrcapByIDNotImplemented() UpdateUrcapByIDResponder {
	return &UpdateUrcapByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.UpdateUrcapByID has not yet been implemented",
		),
	}
}

type UpdateUrcapByIDResponder interface {
	middleware.Responder
	UpdateUrcapByIDResponder()
}
