// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContainerByIDParams creates a new GetContainerByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContainerByIDParams() *GetContainerByIDParams {
	return &GetContainerByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContainerByIDParamsWithTimeout creates a new GetContainerByIDParams object
// with the ability to set a timeout on a request.
func NewGetContainerByIDParamsWithTimeout(timeout time.Duration) *GetContainerByIDParams {
	return &GetContainerByIDParams{
		timeout: timeout,
	}
}

// NewGetContainerByIDParamsWithContext creates a new GetContainerByIDParams object
// with the ability to set a context for a request.
func NewGetContainerByIDParamsWithContext(ctx context.Context) *GetContainerByIDParams {
	return &GetContainerByIDParams{
		Context: ctx,
	}
}

// NewGetContainerByIDParamsWithHTTPClient creates a new GetContainerByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContainerByIDParamsWithHTTPClient(client *http.Client) *GetContainerByIDParams {
	return &GetContainerByIDParams{
		HTTPClient: client,
	}
}

/*
GetContainerByIDParams contains all the parameters to send to the API endpoint

	for the get container by Id operation.

	Typically these are written to a http.Request.
*/
type GetContainerByIDParams struct {

	/* ArtifactName.

	   artifact name of container defined in manifest
	*/
	ArtifactName string

	/* UrcapID.

	   urcapID of urcap defined in manifest
	*/
	UrcapID string

	/* VendorID.

	   vendorID of urcap defined in manifest
	*/
	VendorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContainerByIDParams) WithDefaults() *GetContainerByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContainerByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get container by Id params
func (o *GetContainerByIDParams) WithTimeout(timeout time.Duration) *GetContainerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get container by Id params
func (o *GetContainerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get container by Id params
func (o *GetContainerByIDParams) WithContext(ctx context.Context) *GetContainerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get container by Id params
func (o *GetContainerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get container by Id params
func (o *GetContainerByIDParams) WithHTTPClient(client *http.Client) *GetContainerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get container by Id params
func (o *GetContainerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifactName adds the artifactName to the get container by Id params
func (o *GetContainerByIDParams) WithArtifactName(artifactName string) *GetContainerByIDParams {
	o.SetArtifactName(artifactName)
	return o
}

// SetArtifactName adds the artifactName to the get container by Id params
func (o *GetContainerByIDParams) SetArtifactName(artifactName string) {
	o.ArtifactName = artifactName
}

// WithUrcapID adds the urcapID to the get container by Id params
func (o *GetContainerByIDParams) WithUrcapID(urcapID string) *GetContainerByIDParams {
	o.SetUrcapID(urcapID)
	return o
}

// SetUrcapID adds the urcapId to the get container by Id params
func (o *GetContainerByIDParams) SetUrcapID(urcapID string) {
	o.UrcapID = urcapID
}

// WithVendorID adds the vendorID to the get container by Id params
func (o *GetContainerByIDParams) WithVendorID(vendorID string) *GetContainerByIDParams {
	o.SetVendorID(vendorID)
	return o
}

// SetVendorID adds the vendorId to the get container by Id params
func (o *GetContainerByIDParams) SetVendorID(vendorID string) {
	o.VendorID = vendorID
}

// WriteToRequest writes these params to a swagger request
func (o *GetContainerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param artifactName
	if err := r.SetPathParam("artifactName", o.ArtifactName); err != nil {
		return err
	}

	// path param urcapID
	if err := r.SetPathParam("urcapID", o.UrcapID); err != nil {
		return err
	}

	// path param vendorID
	if err := r.SetPathParam("vendorID", o.VendorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
