// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContainerPortMappingByIDParams creates a new GetContainerPortMappingByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContainerPortMappingByIDParams() *GetContainerPortMappingByIDParams {
	return &GetContainerPortMappingByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContainerPortMappingByIDParamsWithTimeout creates a new GetContainerPortMappingByIDParams object
// with the ability to set a timeout on a request.
func NewGetContainerPortMappingByIDParamsWithTimeout(timeout time.Duration) *GetContainerPortMappingByIDParams {
	return &GetContainerPortMappingByIDParams{
		timeout: timeout,
	}
}

// NewGetContainerPortMappingByIDParamsWithContext creates a new GetContainerPortMappingByIDParams object
// with the ability to set a context for a request.
func NewGetContainerPortMappingByIDParamsWithContext(ctx context.Context) *GetContainerPortMappingByIDParams {
	return &GetContainerPortMappingByIDParams{
		Context: ctx,
	}
}

// NewGetContainerPortMappingByIDParamsWithHTTPClient creates a new GetContainerPortMappingByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContainerPortMappingByIDParamsWithHTTPClient(client *http.Client) *GetContainerPortMappingByIDParams {
	return &GetContainerPortMappingByIDParams{
		HTTPClient: client,
	}
}

/*
GetContainerPortMappingByIDParams contains all the parameters to send to the API endpoint

	for the get container port mapping by Id operation.

	Typically these are written to a http.Request.
*/
type GetContainerPortMappingByIDParams struct {

	/* ArtifactName.

	   artifact name of container defined in manifest
	*/
	ArtifactName string

	/* UrcapID.

	   urcapID of urcap defined in manifest
	*/
	UrcapID string

	/* VendorID.

	   vendorID of urcap defined in manifest
	*/
	VendorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get container port mapping by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContainerPortMappingByIDParams) WithDefaults() *GetContainerPortMappingByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get container port mapping by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContainerPortMappingByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithTimeout(timeout time.Duration) *GetContainerPortMappingByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithContext(ctx context.Context) *GetContainerPortMappingByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithHTTPClient(client *http.Client) *GetContainerPortMappingByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifactName adds the artifactName to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithArtifactName(artifactName string) *GetContainerPortMappingByIDParams {
	o.SetArtifactName(artifactName)
	return o
}

// SetArtifactName adds the artifactName to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetArtifactName(artifactName string) {
	o.ArtifactName = artifactName
}

// WithUrcapID adds the urcapID to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithUrcapID(urcapID string) *GetContainerPortMappingByIDParams {
	o.SetUrcapID(urcapID)
	return o
}

// SetUrcapID adds the urcapId to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetUrcapID(urcapID string) {
	o.UrcapID = urcapID
}

// WithVendorID adds the vendorID to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) WithVendorID(vendorID string) *GetContainerPortMappingByIDParams {
	o.SetVendorID(vendorID)
	return o
}

// SetVendorID adds the vendorId to the get container port mapping by Id params
func (o *GetContainerPortMappingByIDParams) SetVendorID(vendorID string) {
	o.VendorID = vendorID
}

// WriteToRequest writes these params to a swagger request
func (o *GetContainerPortMappingByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param artifactName
	if err := r.SetPathParam("artifactName", o.ArtifactName); err != nil {
		return err
	}

	// path param urcapID
	if err := r.SetPathParam("urcapID", o.UrcapID); err != nil {
		return err
	}

	// path param vendorID
	if err := r.SetPathParam("vendorID", o.VendorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
