// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartContainerByIDParams creates a new StartContainerByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartContainerByIDParams() *StartContainerByIDParams {
	return &StartContainerByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartContainerByIDParamsWithTimeout creates a new StartContainerByIDParams object
// with the ability to set a timeout on a request.
func NewStartContainerByIDParamsWithTimeout(timeout time.Duration) *StartContainerByIDParams {
	return &StartContainerByIDParams{
		timeout: timeout,
	}
}

// NewStartContainerByIDParamsWithContext creates a new StartContainerByIDParams object
// with the ability to set a context for a request.
func NewStartContainerByIDParamsWithContext(ctx context.Context) *StartContainerByIDParams {
	return &StartContainerByIDParams{
		Context: ctx,
	}
}

// NewStartContainerByIDParamsWithHTTPClient creates a new StartContainerByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartContainerByIDParamsWithHTTPClient(client *http.Client) *StartContainerByIDParams {
	return &StartContainerByIDParams{
		HTTPClient: client,
	}
}

/*
StartContainerByIDParams contains all the parameters to send to the API endpoint

	for the start container by Id operation.

	Typically these are written to a http.Request.
*/
type StartContainerByIDParams struct {

	/* ArtifactName.

	   artifact name of container defined in manifest
	*/
	ArtifactName string

	/* UrcapID.

	   urcapID of urcap defined in manifest
	*/
	UrcapID string

	/* VendorID.

	   vendorID of urcap defined in manifest
	*/
	VendorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartContainerByIDParams) WithDefaults() *StartContainerByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start container by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartContainerByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start container by Id params
func (o *StartContainerByIDParams) WithTimeout(timeout time.Duration) *StartContainerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start container by Id params
func (o *StartContainerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start container by Id params
func (o *StartContainerByIDParams) WithContext(ctx context.Context) *StartContainerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start container by Id params
func (o *StartContainerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start container by Id params
func (o *StartContainerByIDParams) WithHTTPClient(client *http.Client) *StartContainerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start container by Id params
func (o *StartContainerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifactName adds the artifactName to the start container by Id params
func (o *StartContainerByIDParams) WithArtifactName(artifactName string) *StartContainerByIDParams {
	o.SetArtifactName(artifactName)
	return o
}

// SetArtifactName adds the artifactName to the start container by Id params
func (o *StartContainerByIDParams) SetArtifactName(artifactName string) {
	o.ArtifactName = artifactName
}

// WithUrcapID adds the urcapID to the start container by Id params
func (o *StartContainerByIDParams) WithUrcapID(urcapID string) *StartContainerByIDParams {
	o.SetUrcapID(urcapID)
	return o
}

// SetUrcapID adds the urcapId to the start container by Id params
func (o *StartContainerByIDParams) SetUrcapID(urcapID string) {
	o.UrcapID = urcapID
}

// WithVendorID adds the vendorID to the start container by Id params
func (o *StartContainerByIDParams) WithVendorID(vendorID string) *StartContainerByIDParams {
	o.SetVendorID(vendorID)
	return o
}

// SetVendorID adds the vendorId to the start container by Id params
func (o *StartContainerByIDParams) SetVendorID(vendorID string) {
	o.VendorID = vendorID
}

// WriteToRequest writes these params to a swagger request
func (o *StartContainerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param artifactName
	if err := r.SetPathParam("artifactName", o.ArtifactName); err != nil {
		return err
	}

	// path param urcapID
	if err := r.SetPathParam("urcapID", o.UrcapID); err != nil {
		return err
	}

	// path param vendorID
	if err := r.SetPathParam("vendorID", o.VendorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
