swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: api.example.com
basePath: /v1
schemes:
  - https

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK

definitions:
  Manifest:
    description: |
      URCap Manifest Specification. The Manifest file is a YAML file defining a multi-artifacts based urcap application. The Manifest.yaml file is located on the top level directory/folder.
    type: object
    properties:
      apiVersion:
        type: string
        example: 1.0.0
        description: "Version (major.minor.patch) of the Manifest specification used. Tools not implementing required version MUST reject the configuration file. \n"
        pattern: ^[a-zA-Z0-9._-]+$
        x-order: 0
        x-nullable: false
      metadata:
        x-order: 1
        $ref: '#/definitions/Metadata'
    required:
    - apiVersion
    - metadata
  Metadata:
    description: Metadata of the urcap
    type: object
    required:
    - vendorID
    - urcapID
    - urcapName
    - vendorName
    - version
    properties:
      vendorID:
        type: string
        example: universal-robots
        description: |
          Company urcap developer ID. The ID is shared among all urcap applications developed by company.
        minLength: 2
        maxLength: 27
        pattern: ^[a-zA-Z0-9._-]+$
        x-order: 0
        x-nullable: false
      urcapID:
        type: string
        example: dockerdaemon
        description: |
          Urcap id for this application. The ID must be unique for each urcap application developed by a company (vendorID).
        minLength: 2
        maxLength: 27
        pattern: ^[a-zA-Z0-9._-]+$
        x-order: 1
        x-nullable: false
      version:
        type: string
        example: 1.0.0
        description: |
          Urcap version (major.minor.patch)
        pattern: ^\d{1}.\d{1}.\d{1}$
        x-order: 2
        x-nullable: false
      vendorName:
        type: string
        example: Universal Robots
        description: |
          Urcap name of this application. This Will be displayed on user interface.
        minLength: 4
        maxLength: 27
        pattern: ^[a-zA-Z0-9_\-\s]+$
        x-order: 3
        x-nullable: false
      urcapName:
        type: string
        example: Docker Daemon
        description: |
          Urcap name of this application. This Will be displayed on user interface.
        minLength: 3
        maxLength: 20
        pattern: ^[a-zA-Z0-9_\-\s]+$
        x-order: 5
        x-nullable: false
      description:
        type: string
        example: Sample gripper URCap
        description: Short description of urcap
        x-order: 6
        x-nullable: false
      copyright:
        type: string
        example: Copyright (c) 2009-2021 Universal Robots. All rights reserved.
        description: Specifies copy rights for the urcap
        x-order: 7
        x-nullable: false
      license:
        type: string
        example: TODO
        description: License of various software/hardware used while developing the urcap
        x-order: 8
        x-nullable: false
  Error:
    description: api error
    type: object
    properties:
      code:
        type: string
        example: missing_field
        description: |
          Error codes.This field contains a string succinctly identifying     the problem.
        x-order: 0
        x-nullable: false
      message:
        type: string
        x-go-type: 
          type: error
          hints:
            kind: interface
        example: The `first_name` field is required.
        description: This field contain a plainly-written, developer-oriented explanation of the solution to the problem in complete, well-formed sentences.
        x-order: 1
        x-nullable: false
      more_info:
        type: string
        format: url
        example: https://docs.api.example.com/v2/users/create_user#first_name
        description: This field SHOULD contain a publicly-accessible URL where information about the error can be read in a web browser.
        x-order: 2
        x-nullable: false
      target:
        x-order: 3
        $ref: '#/definitions/ErrorTarget'
  ErrorTarget:
    description: Error Target Model. This field MAY contain an error target model. Otherwise, it MUST be omitted.
    type: object
    properties:
      name:
        type: string
        example: field
        description: This field MUST contain field, parameter, or header
        enum:
        - field
        - parameter
        - header
        x-order: 0
        x-nullable: false
      value:
        type: string
        example: username
        description: This field MUST contain the name of the problematic field (with dot-syntax if necessary), query parameter, or header.
        x-order: 1
        x-nullable: false
    required:
      - name
      - value
  CompositeError:
    description: composite error
    type: object
    properties:
      code:
        description: http status code
        type: integer
        format: uint32
        x-order: 1
        x-nullable: false
      context: 
        description: context of error
        type: string
        x-order: 0
        x-nullable: false
      errors:
        x-order: 2
        description: list of errors
        type: array
        items:
          $ref: '#/definitions/Error'
    required:
      - errors
  ContextError:
    description: error and context
    type: object
    properties:
      context:
        description: context of the error
        type: string
        x-order: 0
        x-nullable: false
      err:
        description: actual error
        type: string
        x-order: 1
        x-nullable: false
        x-go-type: 
          type: error
          hints:
            kind: interface
  ErrorCode:
    type: object
    properties:
      field: 
        type: string 
      code:
        type: integer
  APIError:
    type: object
    properties:
      trace:
        description: The UUID to uniquely identifying the request
        type: string
        example: 9daee671-916a-4678-850b-10b911f0236d
        x-order: 0
      statusCode:
        description: HTTP status code used for the response
        type: integer
        format: uint16
        example: 500
        x-order: 1
      translationCode:
        $ref: '#/definitions/TranslationCode'
        x-order: 2
      apiContext:
        description: This field contains a snake case string succiently identifying the problem from api context.
        type: string
        example: installation_failed
        x-order: 3
        x-nullable: false
      description:
        description: This field contains description of the problem
        type: string
        x-order: 4
      resolve:
        description: This field explains a possible solution to the problem
        type: string
        example: Please download urcapx file again and try installing again or contact urcap developer
        x-order: 5
      moreInfo:
        description: This filed contains a publicly-accessible URL where information about the error can be read in a web browser
        type: string
        format: url
        example: https://docs.api.example.com/v2/urcaps/installation#corrupted_file
        x-order: 6
      errors:
        description: List of errors
        type: array
        items:
          $ref: '#/definitions/Error'
    required:
      - apiContext
      - errors
  TranslationCode:
    type: object
    properties:
      major:
        description: API context
        type: integer
      minor:
        description: error context
        type: integer

        
