// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"swagger-example/client/container"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationContainerGetContainerPortMappingByIDCmd returns a cmd to handle operation getContainerPortMappingById
func makeOperationContainerGetContainerPortMappingByIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getContainerPortMappingById",
		Short: `Gets host port mapped to the container port`,
		RunE:  runOperationContainerGetContainerPortMappingByID,
	}

	if err := registerOperationContainerGetContainerPortMappingByIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerGetContainerPortMappingByID uses cmd flags to call endpoint api
func runOperationContainerGetContainerPortMappingByID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewGetContainerPortMappingByIDParams()
	if err, _ := retrieveOperationContainerGetContainerPortMappingByIDArtifactNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerGetContainerPortMappingByIDUrcapIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerGetContainerPortMappingByIDVendorIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerGetContainerPortMappingByIDResult(appCli.Container.GetContainerPortMappingByID(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationContainerGetContainerPortMappingByIDParamFlags registers all flags needed to fill params
func registerOperationContainerGetContainerPortMappingByIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerGetContainerPortMappingByIDArtifactNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerGetContainerPortMappingByIDUrcapIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerGetContainerPortMappingByIDVendorIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerGetContainerPortMappingByIDArtifactNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	artifactNameDescription := `Required. artifact name of container defined in manifest`

	var artifactNameFlagName string
	if cmdPrefix == "" {
		artifactNameFlagName = "artifactName"
	} else {
		artifactNameFlagName = fmt.Sprintf("%v.artifactName", cmdPrefix)
	}

	var artifactNameFlagDefault string

	_ = cmd.PersistentFlags().String(artifactNameFlagName, artifactNameFlagDefault, artifactNameDescription)

	return nil
}
func registerOperationContainerGetContainerPortMappingByIDUrcapIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	urcapIdDescription := `Required. urcapID of urcap defined in manifest`

	var urcapIdFlagName string
	if cmdPrefix == "" {
		urcapIdFlagName = "urcapID"
	} else {
		urcapIdFlagName = fmt.Sprintf("%v.urcapID", cmdPrefix)
	}

	var urcapIdFlagDefault string

	_ = cmd.PersistentFlags().String(urcapIdFlagName, urcapIdFlagDefault, urcapIdDescription)

	return nil
}
func registerOperationContainerGetContainerPortMappingByIDVendorIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	vendorIdDescription := `Required. vendorID of urcap defined in manifest`

	var vendorIdFlagName string
	if cmdPrefix == "" {
		vendorIdFlagName = "vendorID"
	} else {
		vendorIdFlagName = fmt.Sprintf("%v.vendorID", cmdPrefix)
	}

	var vendorIdFlagDefault string

	_ = cmd.PersistentFlags().String(vendorIdFlagName, vendorIdFlagDefault, vendorIdDescription)

	return nil
}

func retrieveOperationContainerGetContainerPortMappingByIDArtifactNameFlag(m *container.GetContainerPortMappingByIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("artifactName") {

		var artifactNameFlagName string
		if cmdPrefix == "" {
			artifactNameFlagName = "artifactName"
		} else {
			artifactNameFlagName = fmt.Sprintf("%v.artifactName", cmdPrefix)
		}

		artifactNameFlagValue, err := cmd.Flags().GetString(artifactNameFlagName)
		if err != nil {
			return err, false
		}
		m.ArtifactName = artifactNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerGetContainerPortMappingByIDUrcapIDFlag(m *container.GetContainerPortMappingByIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("urcapID") {

		var urcapIdFlagName string
		if cmdPrefix == "" {
			urcapIdFlagName = "urcapID"
		} else {
			urcapIdFlagName = fmt.Sprintf("%v.urcapID", cmdPrefix)
		}

		urcapIdFlagValue, err := cmd.Flags().GetString(urcapIdFlagName)
		if err != nil {
			return err, false
		}
		m.UrcapID = urcapIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerGetContainerPortMappingByIDVendorIDFlag(m *container.GetContainerPortMappingByIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("vendorID") {

		var vendorIdFlagName string
		if cmdPrefix == "" {
			vendorIdFlagName = "vendorID"
		} else {
			vendorIdFlagName = fmt.Sprintf("%v.vendorID", cmdPrefix)
		}

		vendorIdFlagValue, err := cmd.Flags().GetString(vendorIdFlagName)
		if err != nil {
			return err, false
		}
		m.VendorID = vendorIdFlagValue

	}
	return nil, retAdded
}

// parseOperationContainerGetContainerPortMappingByIDResult parses request result and return the string content
func parseOperationContainerGetContainerPortMappingByIDResult(resp0 *container.GetContainerPortMappingByIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*container.GetContainerPortMappingByIDDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getContainerPortMappingByIdOK is not supported

		return "", respErr
	}

	// warning: non schema response getContainerPortMappingByIdOK is not supported by go-swagger cli yet.

	return "", nil
}
